### PR TITLE
Many systems still use gz 6.x, we shoud support it.

### PR DESCRIPTION
**Pull request by solody**

### CODE REVIEW

**Comment by xy-peng** [comment]
pr的代码是（可能）支持guzzle6，而不支持guzzle7了 @solody 。如果希望pr，应同时兼容6/7。

**Comment by solody** [comment]
Testings fail to static checking in phpstan, the code is which line I've make a detection for  `ClientInterface::VERSION` by `defined()` function, it's actually not a error.

I tested most api call by hand, the patch is work for me.
I think it's posibble to make all functionalities of this project compatible with both Guzzle6 & 7.

Can anyone help to do this?

**Comment by solody** [comment]
> pr的代码是（可能）支持guzzle6，而不支持guzzle7了 @solody 。如果希望pr，应同时兼容6/7。

```php
defined(ClientInterface::class . '::VERSION') ? ClientInterface::VERSION : ClientInterface::MAJOR_VERSION
```

This code is actually compatible with both Guzzle6 & 7.

**Comment by TheNorthMemory** [comment]
Reference discussing on the https://github.com/guzzle/guzzle/pull/2918 and https://github.com/guzzle/psr7/pull/452, `Guzzle6` and `Guzzle\Psr7 1.x` both are `EOL`. It means that there no bugfixing anymore except security fixing. Most application should upgrade to `Guzzle7` thus this PR makes it working on `Guzzle6`.

Any way, while @solody approving https://github.com/solody/wechatpay-php/pull/1, and then let's making this `PR` on the road.

**Pull request closed without merging**
